language: R

cache: packages

sudo: false

warnings_are_errors: false

pandoc: false

os:
  - linux

sudo: required

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 -y

script:
  - export _R_CHECK_FORCE_SUGGESTS_=0
  - mkdir Rchecks
  - R CMD install RcppArmadillo
  - make travis
