language: R

cache: packages

sudo: false

warnings_are_errors: false

pandoc: false

os:
  - linux

addons:
  apt:
    packages:
    - g++-4.8

script:
  - export _R_CHECK_FORCE_SUGGESTS_=0
  - mkdir Rchecks
  - R CMD install RcppArmadillo
  - make travis
